[package]
name = "snake"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic = "0.5"
crossterm = "0.26.1"
rand = "0.8.5"

[profile.release]
opt-level = 3
strip = true
lto = "thin"
panic = "abort"